language: ruby

rvm:
  - 2.2.3

env:
  - DB=postgresql

script:
  - RAILS_ENV=test POLTERGEIST=true bundle exec rake --trace db:migrate spec konacha:run

before_script:
  - gem install i18n-tasks
  - psql -c 'create database tfpullrequests_test' -U postgres

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

sudo: false

addons:
  code_climate:
    repo_token: 2a5e192f091c667d87fbebdf75386384f0676f13cf3011b9cd4a006de7d1edfa

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04f07b2eeecfad3cf278
    on_success: change
