language: ruby

rvm:
  - 2.6.2

before_install:
  - gem update --system
  - gem install bundler

env:
  - DB=postgresql

script:
  - RAILS_ENV=test POLTERGEIST=true bundle exec rake --trace db:migrate spec

before_script:
  - psql -c 'create database tfpullrequests_test' -U postgres

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04f07b2eeecfad3cf278
    on_success: change
