development:
  adapter: postgresql
  encoding: unicode
  database: tfpullrequests_development
  pool: 5 
  host: localhost
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: tfpullrequests_test
  pool: 5
  host: localhost
  password: 
