---
- hosts: all
  vars:
    timezone: UTC
    sys_packages:
      - vim
      - curl
      - python-software-properties
      - build-essential
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libcurl4-openssl-dev
      - libpq-dev
  vars_files:
    - vars/pgsql.yml
  roles:
    - init
    - ruby
    - pgsql
    - app
